services:
  ctfd:
    image: ctfd/ctfd:3.8.0@sha256:61712c4af6e9cddccfafc4503484c8091f6325be286d407595b922dc9552b5ae
    container_name: ctfd
    ports:
      - 8000:8000
    networks:
      - testing
    volumes:
      - ../:/opt/CTFd/CTFd/plugins/ctfd_chall_manager
    environment:
      LOG_LEVEL: DEBUG
      PLUGIN_SETTINGS_CM_API_URL: http://chall-manager:8080
      PLUGIN_SETTINGS_CM_MANA_TOTAL: 10
    depends_on:
      - chall-manager
    healthcheck:
      test: python3 -c 'import requests; requests.get("http://localhost:8000")'
      interval: 10s
      retries: 3
      timeout: 10s

  chall-manager:
    image: ctferio/chall-manager:v0.6.0@sha256:4d0a0379a3c12b2203500a7852856ef7202c7c54d58207fb88d4b8919d5f6add
    container_name: chall-manager
    pull_policy: always
    ports:
      - 8080:8080
    environment:
      SWAGGER: true
      KUBECONFIG: /tmp/config
      OCI_INSECURE: true
    volumes:
      - ~/.kube/config:/tmp/config:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - testing

  chall-manager-janitor:
    image: ctferio/chall-manager-janitor:v0.6.0@sha256:0194e6652aabe59539c1c167e15cc987309c4f49e65c9f3370f358d822246e6e
    container_name: chall-manager-janitor
    pull_policy: always
    environment:
      URL: chall-manager:8080
      TICKER: 30s
    networks:
      - testing

  ctfd-setup:
    image: ctferio/ctfd-setup:v1.7.1@sha256:d555410c10f66eb88a6579078d3f2c9131279e3057c21831a69feb447479b877
    environment:
      URL: http://ctfd:8000
      FILE: /.ctfd.yaml
    volumes:
      - .ctfd.yaml:/.ctfd.yaml
    networks:
      - testing
    depends_on:
      ctfd:
        condition: service_healthy

  registry:
    image: registry:2
    container_name: registry
    ports:
      - 5000:5000
    networks:
      - testing

networks:
  testing:
    driver: bridge
